### PR TITLE
WKWebView improvements

### PR DESCRIPTION
**Pull request by dpa99c**
Hi Niklas,

I've taken your add-webview branch and done some more work on it, mainly implementing the WKWebView navigation delegate functions which makes event callbacks and script injection work (sort of), as well as sorting out some content sizing issues with WKWebView which did not affect UIWebView.

I will probably get around to doing some more (if someone doesn't do first), such as replacing the iframe bridge with a proper WKScriptMessageHandler implementation, but for now what's there is at least a bit of improvement.

I also created a test project against which to validate some of the changes: [cordova-plugin-inappbrowser-test](https://github.com/dpa99c/cordova-plugin-inappbrowser-test/tree/wkwebview).

I hope you find some of this useful. I'm on holiday for 2 weeks from tomorrow, so may be slow to respond to any messages :)

Regards,
Dave.

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Hi Dave

This sounds very promising. Thank you for submitting. I will have a look at this. 

Regards Niklas

**Review by NiklasMerz — APPROVED** [review]
This is very helpfull. From my point of view this is a huge improvement. (Disclaimer: I am not that experienced in iOS debelopment :-) ). I am also thankfull for the test project. I think we are heading the right direction. I will link this PR to the Apache Issue tracker: https://issues.apache.org/jira/browse/CB-7179

**Comment by NiklasMerz** [comment]
Hi Dave

Why did you close this PR? Are you planning to submit your changes via another repo? Thanks for your great work. I was following your changes and they look very promising.

**Comment by dpa99c** [comment]
Oh, I forgot this was open, so it got automatically closed when I deleted the branch. 

But I was just about to update CB-7179 because I have fixed the outstanding issues with my fork and just published it as [cordova-plugin-inappbrowser-wkwebview](https://github.com/dpa99c/cordova-plugin-inappbrowser-wkwebview).

As far as I know, this is now a fully functional implementation of the IAB for iOS using WKWebView (though there probably are some bugs I haven't found yet).

**Pull request closed without merging**
